import { Badge, DateText, JsonBlock } from "../../../components/status";
import { getHealth, getServer, getSnapshot, type Server } from "../../../lib/api";
import { detailCopy } from "../../../lib/copy";

export default async function DetailPage({ params }: { params: Promise<{ serverId:string }> }) {
  const { serverId } = await params;
  const server = await getServer(serverId);
  const [snapshotResult, health] = await Promise.all([getSnapshot(serverId).then(v=>({ok:true as const,v})).catch(e=>({ok:false as const,e})), getHealth(serverId)]);
  const latest = health.items[0];
  return <><section className="hero"><div><p className="eyebrow">{detailCopy.eyebrow}</p><h1>{server.name}</h1><p className="muted">{server.slug} · {server.description}</p></div><Badge value={server.livenessStatus} label={formatLiveness(server.livenessStatus)}/></section><section className="detail"><div className="panel"><h2>{detailCopy.sections.overview}</h2><p><b>연결 방식</b> {formatTransport(server.transport)}</p><p><b>호스팅 유형</b> {formatHosting(server.hostingType)}</p><p><b>환경</b> {formatEnvironment(server.environment)}</p><p><b>접속 정보</b> {server.transport === "streamable_http" ? server.endpointUrl : server.stdioCommand}</p><p><b>태그</b> {server.tags?.join(", ") || "-"}</p></div><div className="panel"><h2>{detailCopy.sections.operations}</h2><p><b>담당 팀</b> {server.ownerTeam}</p><p><b>문의</b> {server.contact}</p><p><b>저장소</b> {server.repositoryUrl || "-"}</p><p><b>운영 문서</b> {server.runbookUrl || "-"}</p><p><b>최근 상태 확인</b> {latest ? `${formatLiveness(latest.status)} · ${latest.latencyMs}ms` : "기록 없음"}</p><p><b>최근 동기화</b> <DateText value={server.lastSyncAt}/> · {formatSyncStatus(server.lastSyncStatus)}</p>{server.lastSyncError ? <p className="failed"><b>동기화 오류</b> {server.lastSyncError}</p> : null}</div></section>{server.transport === "stdio" ? <LocalMcpPanel server={server}/> : null}{snapshotResult.ok ? <SnapshotView snapshot={snapshotResult.v}/> : <div className="panel section"><h2>{detailCopy.sections.snapshot}</h2><p className="muted">{detailCopy.emptySnapshot}</p></div>}</>;
}

function LocalMcpPanel({ server }: { server: Server }) {
  return <section className="panel section"><h2>{detailCopy.sections.localMcp}</h2><p className="muted">이 서버는 사용자 환경에서 실행한 뒤 MCP 클라이언트에 연결합니다. Web UI는 로컬 stdio 프로세스를 실행하지 않으며, 실행 파일과 접근 권한은 담당 팀의 저장소 또는 운영 문서를 기준으로 확인하세요.</p><div className="infoGrid"><p><b>실행 명령</b><code>{[server.stdioCommand, ...(server.stdioArgs ?? [])].filter(Boolean).join(" ") || "-"}</code></p><p><b>필요 환경 변수</b>{server.stdioEnvKeys?.length ? server.stdioEnvKeys.join(", ") : "-"}</p><p><b>배포 위치</b>{server.repositoryUrl || server.runbookUrl || server.contact || "담당 팀 문의"}</p></div></section>;
}

function SnapshotView({ snapshot }: { snapshot: Awaited<ReturnType<typeof getSnapshot>> }) { return <section className="section"><div className="panel"><h2>{detailCopy.sections.snapshot}</h2><p><b>프로토콜</b> {snapshot.protocolVersion || "-"}</p><p><b>스냅샷 해시</b> {snapshot.snapshotHash}</p><p><b>수집 시각</b> <DateText value={snapshot.capturedAt}/></p>{snapshot.warnings?.length ? <p className="muted">주의: {snapshot.warnings.join(", ")}</p> : null}</div><CapabilityTable title={detailCopy.sections.tools} items={snapshot.tools} columns={["name","title","description","inputSchema","outputSchema"]}/><CapabilityTable title={detailCopy.sections.resources} items={snapshot.resources} columns={["uri","name","title","mimeType","description"]}/><CapabilityTable title={detailCopy.sections.prompts} items={snapshot.prompts} columns={["name","title","description","arguments"]}/><details className="panel section"><summary>{detailCopy.sections.raw}</summary><JsonBlock value={snapshot}/></details></section> }
function CapabilityTable({ title, items, columns }: { title:string; items:Record<string,unknown>[]; columns:string[] }) { return <div className="section"><h2>{title}</h2><table className="table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{items.map((item,i)=><tr key={i}>{columns.map(c=><td key={c}>{typeof item[c] === "object" ? <code>{JSON.stringify(item[c])}</code> : String(item[c] ?? "")}</td>)}</tr>)}</tbody></table>{items.length===0?<div className="empty">{detailCopy.emptyItems}</div>:null}</div> }
function formatTransport(value: string) { return value === "streamable_http" ? "원격 HTTP" : value === "stdio" ? "로컬 실행" : value; }
function formatLiveness(value: string) { return { healthy: "정상", degraded: "주의", offline: "오프라인", unknown: "미확인" }[value] ?? value; }
function formatEnvironment(value: string) { return { dev: "개발", stg: "스테이징", prod: "운영", shared: "공용" }[value] ?? value; }
function formatHosting(value: string) { return { owner_hosted: "팀 운영", platform_hosted: "플랫폼 운영", external: "외부 운영", local_stdio: "사용자 환경 실행" }[value] ?? value; }
function formatSyncStatus(value: string) { return { never: "동기화 전", success: "성공", failed: "실패" }[value] ?? value; }
