apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-hub.fullname" . }}-config
data:
  MCPHUB_AUTH_MODE: {{ .Values.config.authMode | quote }}
  MCPHUB_API_URL: {{ .Values.config.apiUrl | quote }}
  MCPHUB_WORKER_INTERVAL: {{ .Values.config.workerInterval | quote }}
  MCPHUB_SYNC_TIMEOUT: {{ .Values.config.syncTimeout | quote }}
  MCPHUB_ENABLE_SERVER_STDIO_EXEC: {{ .Values.config.enableServerStdioExec | quote }}
