{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mcp-hub.fullname" . }}
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - {}
  egress:
    - {}
{{- end }}
