import Link from "next/link";
import { Badge, DateText } from "../../components/status";
import { catalogSummary, listServers } from "../../lib/api";

export default async function CatalogPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const params = await searchParams;
  const [summary, servers] = await Promise.all([catalogSummary(), listServers(params)]);
  return <><section className="hero"><div><p className="eyebrow">Internal catalog</p><h1>조직 MCP 서버 카탈로그</h1><p className="muted">Hub는 MCP 서버를 호스팅하지 않습니다. 운영 책임은 각 owner team에 있습니다.</p></div></section><section className="grid">{[["전체",summary.total],["streamable_http",summary.streamableHttp],["stdio",summary.stdio],["healthy",summary.healthy],["sync 실패",summary.syncFailed],["stale snapshot",summary.staleSnapshots]].map(([label,value])=><div className="card metric" key={label}><span className="muted">{label}</span><strong>{value}</strong></div>)}</section><form className="filters"><input name="q" placeholder="검색" defaultValue={params.q}/><select name="transport" defaultValue={params.transport ?? ""}><option value="">transport</option><option value="streamable_http">streamable_http</option><option value="stdio">stdio</option></select><select name="livenessStatus" defaultValue={params.livenessStatus ?? ""}><option value="">liveness</option><option value="healthy">healthy</option><option value="degraded">degraded</option><option value="offline">offline</option><option value="unknown">unknown</option></select><select name="environment" defaultValue={params.environment ?? ""}><option value="">env</option><option value="dev">dev</option><option value="stg">stg</option><option value="prod">prod</option><option value="shared">shared</option></select><input name="ownerTeam" placeholder="owner team" defaultValue={params.ownerTeam}/><input name="tag" placeholder="tag" defaultValue={params.tag}/></form><table className="table"><thead><tr><th>서버</th><th>Transport</th><th>상태</th><th>Owner</th><th>Env</th><th>Capabilities</th><th>Last sync</th><th>Tags</th></tr></thead><tbody>{servers.items.map(s=><tr key={s.id}><td><Link href={`/servers/${s.slug}`}>{s.name}</Link><div className="muted">{s.description}</div></td><td><Badge value={s.transport}/></td><td><Badge value={s.livenessStatus}/></td><td>{s.ownerTeam}</td><td>{s.environment}</td><td>{s.toolCount} tools · {s.resourceCount} resources · {s.promptCount} prompts</td><td><DateText value={s.lastSyncAt}/><div className="muted">{s.lastSyncStatus}</div></td><td>{s.tags?.join(", ")}</td></tr>)}</tbody></table>{servers.items.length===0?<div className="empty">등록된 MCP 서버가 없습니다.</div>:null}</>;
}
